Ferlab-Ste-Justine/clin-pipelines-dags

- dags/lib/config.py
We can rollback to this version. The important changes has been done in prod repo inside the executors configs like this: https://github.com/Ferlab-Ste-Justine/cqgc-prod-kubernetes-environments/blob/main/prod/apps/spark-jobs/index-elasticsearch-etl/configs.yml#L11
> feat: CLIN-1427 - revert spark image 3.1.2

- dags/etl_import_orphanet.py
This import is small without MD5, so we download it + md5 it and compare with previous computed MD5, if different then save into S3
Also the download needs 2 orphanet files to start the Import so this file import both of them.
> feat: CLIN-1487 - import orphanet

- dags/lib/config.py
- dags/lib/doc/qa.py
Les variants de la table normalized_snv doivent être unique par service_request_id et non par patient_id
> fix: CLIN-1872 no_dup_snv sur service_request_id

- dags/lib/config.py
- dags/lib/doc/qc.py
- dags/lib/groups/qc.py
Add dictionary DataTests
- dictionary_cnv
- dictionary_consequences
- dictionary_donors
- dictionary_snv
L'objectif de ces tests est d'attraper les potentielles nouvelles valeurs en PROD qui ne sont pas incluses dans les dictionnaires harcodés des facettes.
> feat: CLIN-1379 Add dictionary DataTests

- dags/etl_import_cosmic.py
- dags/lib/config.py
Le fichier téléchargé automatiquement pour cosmic_gene n'était pas le bon. Le fichier adéquat est seulement disponible en téléchargement manuel pour le moment. J'ai donc désactivé le téléchargement automatique de ce fichier. Il faut aussi rouler la job d'import en initial pour nettoyer le schéma de l'ancien fichier qui était erroné.
> chore: CLIN-2182 Set import gene census to initial

- dags/lib/franklin.py
Test en local concluant sur:
Les deux sont ignores
> feat: CLIN-2645 filter family

- dags/lib/doc/qc.py
- dags/lib/groups/qc.py
- complements #CLIN-2938
[CLIN-2938](https://ferlab-crsj.atlassian.net/browse/CLIN-2938)
[CLIN-2938]: https://ferlab-crsj.atlassian.net/browse/CLIN-2938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: CLIN-2938 Add freq RQDM tumor DataTests

- .gitignore
- dags/lib/config.py
- dags/lib/operators/nextflow.py
- dags/lib/operators/spark.py
- dags/lib/operators/utils/utils_pod.py
- dags/test_nextflow_operator.py
- doc/test/docker_compose_and_minikube_setup.md
- doc/test/minikube_setup.md
- doc/test/nextflow_setup.md
- doc/test/readme.md
- doc/test/templates/README.md
- doc/test/templates/airflow/airflow.yaml
- doc/test/templates/airflow/values.yaml
- doc/test/templates/nextflow/minio_pv.yaml
- doc/test/templates/nextflow/mock_minio.yaml
- doc/test/templates/nextflow/nextflow.yaml
- doc/test/templates/nextflow/nextflow_config.yaml
**Description**
To facilitate team collaboration, this PR introduces generic Nextflow code that can be reused and evolved by the team to implement Nextflow DAGs.
Additionally, we introduce a generic test nextflow DAG that allows launching ad hoc nextflow jobs from the Airflow UI. This feature enables users to test and validate their pipelines in a controlled environment before deploying them to production.
In the short term, we would like to use this DAG for testing an SNV clustering nextflow pipeline. To test with realistic data, it will probably need to run in the staging environment. Please keep this in mind during the review. 
Associated JIRA ticket:
https://ferlab-crsj.atlassian.net/browse/CLIN-3138
**Local tests**
I tested running the nextflow DAG locally with minikube. 
I included …
> feat: CLIN-3138 Add nextflow test dag

- dags/lib/operators/nextflow.py
- dags/test_nextflow_operator.py
- doc/test/minikube_setup.md
The default DAG parameters were used instead of the parameters configured in the UI. This commit addresses this issue.
Other changes:
- Bump the airflow helm chart version in the minikube setup procedure to match the version in QA.
- Fix style warnings reported by flake8
Associated JIRA:
https://ferlab-crsj.atlassian.net/browse/CLIN-3230
**Tests:**
I used a local setup with minikube to start airflow and installed components required by the nextflow dag.  See doc/test/nextflow_setup.md
**1) Execute nextflow dag with default parameters**
- The dag run was successful 
- I could see that the default nextflow hello command was executed on the pod through the task logs.
**2) Execute nextflow dag with manually provided command arguments**
In the airflow UI, I executed the nextflow dag with the …
> fix: CLIN-3230 use parameters configured in airflow UI in nextflow dag

- dags/lib/operators/nextflow.py
Fix broken etl.py dag (nextflow group) that is caused by a typo when specifying a nextflow operator attribute.
**Test procedure**
I run the problematic task (nextflow.svclustering_parental_origin) locally in a test dag, pointing on the qa etl cluster.
I could see that the test dag completed successfully and that nextflow jobs were run.
The dags take about 8 minutes to execute and consume, roughly, up to 10-15 pods in the cluster.
Below is a description of the procedure that I used. 
1. Create a minimalist test dag isolating the nextflow task posing problem:
```
from datetime import datetime
from typing import List
from airflow import DAG
from airflow.decorators import task
from airflow.models import DagRun
from airflow.models.param import Param
from lib.tasks import batch_type, nextflow …
```
> fix: CLIN-3267 typo in nextflow pipeline revision

- dags/etl.py
- dags/etl_germline.py
- dags/etl_ingest.py
- dags/etl_migrate.py
- dags/etl_reset_enrich_cnv.py
- dags/etl_somatic_tumor_only.py
- dags/lib/config.py
- dags/lib/groups/ingest/ingest_germline.py
- dags/lib/groups/migrate/migrate_germline.py
- dags/lib/groups/normalize/normalize_germline.py
- dags/lib/tasks/enrich.py
- dags/lib/tasks/nextflow.py
* Move nextflow parental origin tasks to `etl_ingest`.
* Optionally pass `batch_id` to `enrich.cnv`. If no `batch_id` is passed to `etl` DAG, run `enrich.cnv` for all batches. Same behavior as `enrich.snv_somatic`.
* Put `enrich.cnv` and `enrich.snv_somatic` tasks into subgroups to simplify `etl` DAG graph.
> feat: CLIN-3207 Normalize nextflow svcpo + Pass batch_id to enrich_cnv

- dags/etl_import_gnomad_v4_genomes.py
- dags/lib/config.py
Question:
- I used `destination_prefix = f'raw/landing/gnomad_v{LATEST_VERSION.replace(".", "_")}/{seq_type}'` where destination will have a "4_1" in the path, would it be preferable to have only "4" instead?
Note:
- I had to use the extra connection config for the gnomad connection to work
```
{
"config_kwargs": {
"signature_version": "unsigned"
}
}
```
> feat: CLIN-3561 new etl to download gnomad genomes

- dags/lib/config_nextflow.py
By default, the new version 1.2.0 will only include variants with the filter column set to PASS.
If needed, this behaviour can be turned off by setting parameter include_only_pass_variants to false.
> feat: CLIN-3678 Update ferlabsvclustering nextflow pipeline to 1.2.0

- dags/lib/config_nextflow.py
- dags/lib/tasks/nextflow.py
- dags/test_nextflow_variant_annotation.py
This pull request introduces a task to launch the Nextflow variant annotation pipeline, i.e. this pipeline:
https://github.com/Ferlab-Ste-Justine/Post-processing-Pipeline
It also includes a test DAG to validate the task until the preliminary ETL tasks are implemented.
For now, the DAG will appear only in QA.
**Tests**
Started Airflow locally with Docker Compose and launched the test DAG on the QA Kubernetes ETL cluster. The DAG was executed successfully.
I did a rebase and minor cosmetic changes after this test, so it would be a good idea to re-test.  Will wait to see if there are corrections requested before doing so.
> feat: CLIN-3267 add variant annotation nextflow task

- dags/etl_run.py
- dags/lib/datasets.py
- requirements
Retrieve all sequencing IDs that share the same analysis ID as the given sequencing IDs from the `enriched_clinical` Delta table directly in Airflow, using `pandas` and `deltalake` libraries in a `PythonVirtualEnvOperator`.
* ✨ Added `get_all_sequencing_ids` task to `etl_run.py.`
* ✨ Added a `datasets.py` file to create a common place where to store our dataset locations.
* ✨ Added `deltalake===0.24.0` to `requirements.txt`.
Here is an output example using QA data locally:
```
[2025-02-07, 16:10:06 EST] {process_utils.py:191} INFO - distinct_sequencing_ids: {'1261530', '1261482'}
[2025-02-07, 16:10:06 EST] {process_utils.py:191} INFO - filtered_df:     service_request_id analysis_service_request_id
[2025-02-07, 16:10:06 EST] {process_utils.py:191} INFO - 0              1261482 …
```
> feat(etl_run): CLIN-3728 Extract all sequencing IDs from enriched_clinical

- dags/etl_cnv_frequencies.py
Updating the `start_date` time alone was not enough to ensure the DAG runs at 2 AM. To enforce this schedule, we need to use a CRON expression in the `schedule` parameter.
[CLIN-3879](https://ferlab-crsj.atlassian.net/browse/CLIN-3879)
[CLIN-3879]: https://ferlab-crsj.atlassian.net/browse/CLIN-3879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CLIN-3879 Enforce etl cnv frequencies schedule at 2 AM

- dags/etl_run.py
In QA, staging and prod environments, the host is set in the connection extras, and not in the connection host property.
[CLIN-3728](https://ferlab-crsj.atlassian.net/browse/CLIN-3728)
[CLIN-3728]: https://ferlab-crsj.atlassian.net/browse/CLIN-3728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(get_all_sequencing_ids): CLIN-3728 Get host from connection extra

- dags/etl.py
- dags/etl_cnv_frequencies.py
- dags/etl_delete_previous_releases.py
- dags/etl_qc_es.py
- dags/lib/groups/index/delete_previous_releases.py
- dags/lib/tasks/es.py
Small changes (improvements?) to PROD behavior:
Schedules DAGs that can now be disabled:
> feat: CLIN-3982 cnv frequencies + delete release

- dags/lib/config_operators.py
Passing the argument as string is causing an unmarshall error when airflow tries to create the pod.
> fix: BIOINFO-37 use string to pass filter batch size argument

- dags/etl_run.py
- dags/lib/config_nextflow.py
- dags/lib/tasks/nextflow/exomiser.py
- dags/lib/tasks/nextflow/post_processing.py
- dags/lib/utils_etl_tables.py
- dags/test_nextflow_post_processing.py
The main goal of this pull request is to add an extra task in dag etl_run.py to launch the nextflow post processing pipeline.
Additionally, it includes a slight refactoring of the previous steps that prepare the input files (details below).
- ✨  Introduced an extra task in etl_run.py to launch the nextflow post-processing pipeline.
- ♻️   The analysis ids hash is now created within etl_run.py via a dedicated task, allowing it to be reused across multiple tasks. (Recommendation from @laurabegin)
- ♻️  Created module utils_etl_tables to group utils functions involving etl table manipulations
- ♻️  Refactored the code to reduce duplication with another task in the same DAG while adding the new task.
The goal was to reduce the dag body and reduce code duplication. If additional tasks are …
> feat: CLIN-3730 launch nextflow post processing pipeline

- dags/etl_run.py
Small correction to avoid duplicated slack notifications when starting the dag.
The `on_execute_callback` attribute defined in the `@task(task_id='params_validate', on_execute_callback=Slack.notify_dag_start)` annotation needs to be overridden. 
Previously, we were overriding `on_success_callback` attribute instead, which had no effect in this case.
> fix: CLIN-3410 fix duplicated slack notification on start

- dags/lib/config_nextflow.py
- dags/lib/tasks/nextflow/cnv_post_processing.py
- dags/test_nextflow_cnv_post_processing.py
This pull request introduces a nextflow task to launch the `cnv-post-processing` pipeline.
A test DAG (`test_nextflow_cnv_post_processing.py`) is included to validate the task. The test DAG is configured to appear only in the QA environment when the `show_test_dags` variable is set to true.
Note:
- For now, the output files are stored under `cqgc-qa-app-datalake/nextflow`, consistent with the other pipelines.
We considered using the new nextflow bucket (cqgc-qa-app-nextflow) immediately, but this change is delicate as it requires modifying configurations shared by multiple pipelines. To ensure proper tracking and QA, we propose updating the global nextflow bucket configuration in a separate pull request.
- new nextflow task to launch cnv-post-processing pipeline
- new dag …
> feat:CLIN-4404-add-nextflow-task-for-cnv-post-processing-pipeline

- dags/lib/tasks/batch_type.py
We observed instability with the `detect_batch_type` task when parallel execution was allowed. 
To address this, we introduce a restriction to ensure that only one instance of the task runs at a time.
This change aims to improve stability by avoiding potential issues such as memory overload or Delta Lake connection problems.
- We set the parameter `max_active_tis_per_dag` to `1` on task `detect_batch_type` to force sequential execution
- Execute the task locally via a test dag and verify that it can still be executed succesfully ✅ 
- Execute the begginning of the etl.run dag, until detect_batch_type task locally.  Check that the detect_batch_type tasks are run sequentially. ✅ 
Airflow documentation:
https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dynamic-task …
> fix: CLIN-4321 avoid running detect_batch_type map tasks in parallel

- dags/lib/config.py
- dags/lib/config_nextflow.py
- dags/lib/tasks/nextflow/svclustering.py
- dags/lib/tasks/nextflow/svclustering_parental_origin.py
This pull request move nextflow pipelines inputs and outputs to nextflow buckets.
We restrict to tables containing raw input and output data. Intermediate delta tables derived from nextflow pipelines output data are not touched.
This pull request is linked to a companion PR in clin-pipeline-dags and should be merged and deployed simultaneously: 
https://github.com/Ferlab-Ste-Justine/clin-variant-etl/pull/460
This involves our 4 nextflow pipelines:
- svclustering
- svclustering_parental_origin
- post_processing
- cnv_post_processing
To deal with already existing data, a manual migration procedure will need to be applied.  See the script migration.sh that is in the attachments on the JIRA:
https://ferlab-crsj.atlassian.net/browse/CLIN-4284
- Update input/output pipelines paths
- Run dags / …
> feat: CLIN-4284 move nextflow pipelines inputs and outputs to nextflow bucket

- dags/lib/config.py
The Spark JAR version was mistakenly updated only for the production environment. This commit ensures that all environments (QA, Staging, and Production) use the same version to maintain consistency.
> fix: CLIN-4284 align spark jar version across all environments

- README.md
- dags/lib/config.py
- dags/lib/franklin.py
- pytest.ini
- requirements.txt
- tests/conftest.py
- tests/dags/conftest.py
- tests/dags/test_dags.py
- tests/dags/test_etl_import_franklin.py
- tests/lib/test_franklin.py
- variables.json
- Introduced a `TEST` environment in `config.py`  
- Added TODO comments in `franklin.py` for code sections that need refactoring  
- Updated `requirements.txt`  
- Created a `pytest.ini` file for Pytest configuration  
- Fixed the `franklin_password` value in `variables.json`  
- Added a global DAG bag test  
- Added unit tests for `etl_import_franklin`  
- Added unit tests for Franklin utilities  
- Documented how to run tests in `README.md`
---
Some test setup code is duplicated across unit tests. I considered refactoring it into fixtures but chose to keep it simple for now.  
Let me know if you’d prefer I refactor those setups into reusable fixtures.  
---
1. Update your environment with the latest `requirements.txt`  
2. Run `pytest`  
3. The test output should look like:  
---
> feat: CLIN-4604 Add franklin utils unit tests

- dags/lib/config.py
Bumping clin-variant-etl version to 3.13.0. Change is done in QA environment only.
This version is using new partitioning by analysis_id and bioinfo_analysis_code for tables normalized_snv_somatic and enriched_snv_somatic
> feat: CLIN-4690 update clin-variant-etl version to 3.13.0

- dags/lib/config.py
This will leverage the new partitioning by analysis id for the following etl tables: normalized_cnv, normalized_cnv_somatic_tumor_only, enriched_cnv.
> feat: CLIN-4759 bumping clin-variant-etl version to 3.14.0

- dags/etl.py
- dags/etl_ingest.py
- dags/etl_migrate.py
- dags/etl_notify.py
- dags/etl_run.py
- dags/lib/groups/ingest/ingest_germline.py
- dags/lib/groups/ingest/ingest_somatic_tumor_normal.py
- dags/lib/groups/ingest/ingest_somatic_tumor_only.py
- dags/lib/groups/migrate/migrate_germline.py
- dags/lib/groups/migrate/migrate_somatic_tumor_normal.py
- dags/lib/groups/migrate/migrate_somatic_tumor_only.py
- dags/lib/groups/normalize/normalize_germline.py
- dags/lib/groups/normalize/normalize_somatic_tumor_normal.py
- dags/lib/groups/normalize/normalize_somatic_tumor_only.py
- dags/lib/operators/spark_etl.py
- dags/lib/tasks/batch_type.py
- dags/lib/tasks/normalize.py
- dags/lib/tasks/params_validate.py
- dags/lib/utils.py
- dags/lib/utils_etl.py
- docker-compose.yaml
PR qui rajoute la possibilitee de passer `sequencing_ids` en param de:
- `etl`
- `etl_ingest`
Cela s'inscrit dans la futur flot ou `etl_run`, une fois la generation des VCFs, Exomisers termine, pourra appeler `etl` avec la liste des sequening_ids et realiser une release comme on a l'habitude de faire de facon transparente.
*La scope de la PR a ete volontairement reduit et n'inclut pas la partie ou les ids sont propages dans le code et envoyes vers les ETLs, ca faisait trop gros.*
**Le but de la PR est aussi de rester retro-compatible avec l'existant, tout les endroit qui utilisent `detect_batch_type` pour savoir ce qui doit etre skip ou pas.**
Voici a quoi ressemble `etl`:
Vous avez ici un exemple ou un ensemble de batchs ainsi que de sequencings ont ete envoyes en param, `etl` accepte ce …
> feat: CLIN-4328 - batch ids and sequencing ids Part 1

- dags/etl_migrate.py
- dags/etl_migrate_batch.py
- dags/lib/groups/migrate/migrate_germline.py
- dags/lib/groups/migrate/migrate_somatic_tumor_normal.py
- dags/lib/groups/migrate/migrate_somatic_tumor_only.py
- dags/lib/groups/normalize/normalize_germline.py
- dags/lib/groups/normalize/normalize_somatic_tumor_normal.py
- dags/lib/groups/normalize/normalize_somatic_tumor_only.py
- dags/lib/tasks/batch_type.py
- dags/lib/tasks/normalize.py
> fix: CLIN-4681 - etl migrate expand + auto batch_ids

- dags/etl_run.py
In this PR, we remove the get-all-sequencing-ids-task from the etl_run DAG.
We identified that, after the recent CLIN-4799 refactoring,  it is no longer used and unnecessarily slows down the DAG execution.
**Tests**
Tested locally (pointing on QA) with a valid germline sequencing id to make sure to pass in all the dag steps. Everything looks good.
> feat: CLIN-4799 removed unused task get-all-sequencing-ids in dag etl

- dags/etl_import_topmed_bravo.py
- dags/lib/config.py
- dags/lib/utils_etl.py
- dags/lib/utils_s3.py
Pour récupérer les fichiers, il faut se connecter avec un compte Google sur le site, récupérer le cookie puis le donner en entré au DAG. Avant ce paramètre était rentré dans Vault puis utilisé par le DAG, cependant comme ce cookie semble changer régulièrement et qu'on en a besoin seulement au moment de l'exécution, j'ai choisi de supprimer le paramètre de la config pour le mettre en paramètre du DAG à fournir au moment de l'exécution.
Le DAG doit être exécuté tous les 3 mois. Comme cela nécessite une opération manuelle, il faudrait un rappel au 3 mois. J'ai mis un Schedule pour que le DAG se lance au 3 mois. Il sera en échec ce qui nous donnerais une sorte d'alerte. Est-ce que ca parait suffisant ou alors, il serait mieux d'enlever le schedule et de trouver une autre façon de faire ?
La …
> feat CLIN-4902: Schedule DAG and update code to new file an url
