dags/lib/groups/qc.py

Ajout des datatests de non duplication et de comparaison des variants pour les différentes tables.

feat: CLIN-1379 Add variantlist datatests

---

dags/lib/config.py

Requires: https://github.com/Ferlab-Ste-Justine/csv-to-fhir/pull/17

feat: CLIN-1458 - qa/staging files

---

dags/lib/config.py

Fix d'un bug prod only a retrofit: https://github.com/Ferlab-Ste-Justine/clin-variant-etl/pull/217

fix: CLIN-1427 - bump version staging/prod etl

---

dags/etl_import_human_genes.py

This import is small without MD5, so we download it + md5 it and compare with previous computed MD5, if different then save into S3

feat: CLIN-1486 - import human genes

---

dags/lib/doc/qa.py
dags/lib/doc/qc.py
dags/lib/groups/qa.py
dags/lib/groups/qc.py

Ajout de tests pour les tables dans le dag etl_qa
- Tables non vides
Ajout de tests pour Varsome dans le dag etl_qc
- Les variants annotés
- Les variants non annotés
- Mise-à-jour de l'annotation après 7 jours
- Mise-à-jour de l'annotation pas avant 7 jours

feat: CLIN-1379 Add Varsome and non empty tables tests

---

dags/lib/config.py

- CLIN-1521 Error in ColumnsContainSameValueVariantCentric
- CLIN-1602 - Gnomad

feat: CLIN-1602 - qa qc

---

dags/etl.py

feat: CLIN-1645 - typos

---

dags/lib/doc/qc.py

Ajustements à la doc des tests (variants de la dernière batch seulement)
- variants_should_be_reannotated
- variants_should_not_be_reannotated

feat: CLIN-1379 Ajust Varsome tests doc

---

dags/lib/config.py

feat: CLIN-1379 - bump etl

---

dags/etl_import_spliceai.py
dags/lib/config.py

- Run indel_table and snv_table tasks in parallel
- Add final EmptyOperator to notify slack after both tables are imported

feat(spliceai): CLIN-1601 Add tasks for table import

---

dags/etl.py
dags/etl_ingest.py
dags/lib/groups/ingest.py

Exract the `ingest` part of the ETL dag and add a new `etl_ingest` dag.
`etl_ingest` can be used to recompute a specific batch without running all the ETLs

fix: extract ingest DAG

---

dags/lib/config.py

feat: CLIN-1682 - ETL prod

---

dags/etl_import_gnomad_constraint.py
dags/lib/config.py

feat(gnomad): CLIN-1669 Import gnomad constraint metrics file

---

dags/lib/config.py
dags/lib/doc/qc.py
dags/lib/groups/qa.py
dags/lib/groups/qc.py

Dag qc
- fromVCF
- Table normalized_snv
- Table normalized_variants
- frequency
- frequency_RQDM - total
- frequency_RQDM - affected
- frequency_RQDM - non_affected
- frequencies_by_analysis - total
- frequencies_by_analysis - affected
- frequencies_by_analysis - non_affected

feat: CLIN-1379 Add fromVCF and frequency DataTest

---

dags/lib/config.py

feat: CLIN-1741 - bump prod etls

---

dags/etl_cleanup.py

Better delete of indexes by envs.

feat: CLIN-1746 - cleanup index with hash

---

dags/lib/doc/qa.py
dags/lib/groups/qa.py

Add Non duplication tests
- normalized_consequences
- consequences

feat: CLIN-1788 Add Non duplication consequences tests

---

dags/lib/doc/qa.py
dags/lib/groups/qa.py

Adjustments to DataTests
- CLIN-1756
- CLIN-1785

feat: CLIN-1756_CLIN-1785 Adjustments to DataTests

---

dags/lib/config.py
dags/lib/doc/qa.py

Documentation du test no_dup_gnomad sur gnomad_genomes_v3 au lieu de gnomad_genomes_3_0

feat: CLIN-1794 Adjustment to DataTest

---

dags/lib/groups/qa.py
dags/lib/groups/qc.py

J'ai change la config spark de QA et QC en PROD
Retrofit vers QA/STAGING

feat: CLIN-1876 - qa/qc spark config

---

dags/lib/config.py

Contient le fix du mapping `rank`

feat: CLIN-1884 bump ETLs

---

dags/lib/config.py

fix: CLIN-1884 - bump ETLs

---

dags/etl.py
dags/lib/config.py

Retrofit if indexer is working

feat: CLIN-1894 - indexer context

---

dags/etl_import_panels.py
dags/lib/config.py
dags/lib/groups/ingest.py

* Change `vcf` and `external` packages to `normalized`
* Add normalized exomiser task to ingest group

refactor: CLIN-1949 Change vcf + external packages to normalized

---

dags/lib/config.py

feat: CLIN-1970

---

dags/etl.py
dags/lib/config.py
dags/lib/doc/qa.py
dags/lib/groups/qa.py

feat: CLIN-1949 Add enrich_snv task + Refactor QA group for enrich_snv

---

dags/lib/config.py

feat: CLIN-1998 release

---

dags/lib/config.py

feat: CLIN-2012 -release

---

dags/lib/config.py

Ca + lancer etl_import_dbnsfp and QA ... :crossed_fingers: S3 est a jour
etl_qc tourne en prod donc pas maintenant ...

feat: CLIN-1946 - bump ETLs

---

dags/lib/groups/ingest.py

Add new SNV Somatic Ingest DAG
https://github.com/Ferlab-Ste-Justine/clin-variant-etl/pull/304

feat: CLIN-2026 - add somatic dag

---

dags/lib/groups/ingest.py

feat: CLIN-2026 - disable somatic

---

dags/etl.py
dags/lib/config.py
dags/lib/groups/ingest.py

Rajout des deux nouveaux DAGs somatic

feat: CLIN-2026 - somatics dags

---

dags/lib/config.py

feat: CLIN-2124 - release

---

dags/etl.py
dags/etl_import_1000_genomes.py
dags/etl_import_clinvar.py
dags/etl_import_cosmic.py
dags/etl_import_dbnsfp.py
dags/etl_import_dbsnp.py
dags/etl_import_ddd.py
dags/etl_import_ensembl.py
dags/etl_import_genes.py
dags/etl_import_gnomad_constraint.py
dags/etl_import_hpo.py
dags/etl_import_human_genes.py
dags/etl_import_omim.py
dags/etl_import_orphanet.py
dags/etl_import_panels.py
dags/etl_import_rare_variant.py
dags/etl_import_refseq_annotation.py
dags/etl_import_spliceai.py
dags/etl_import_topmed_bravo.py
dags/etl_import_varsome.py
dags/etl_reset_enrich_cnv.py
dags/etl_reset_enrich_consequences.py
dags/etl_reset_enrich_variants.py
dags/lib/config.py
dags/lib/groups/ingest_batch.py
dags/lib/groups/ingest_fhir.py

refactor: CLIN-2152 Name arguments

---

dags/etl.py
dags/etl_ingest.py
dags/etl_migrate.py
dags/lib/config.py
dags/lib/groups/ingest_batch.py

https://github.com/Ferlab-Ste-Justine/clin-variant-etl/pull/323

feat: CLIN-2164 - normalized-coverage-by-gene

---

dags/lib/config.py

feat: CLIN-2188 release

---

dags/lib/config.py
dags/lib/groups/ingest_batch.py

feat: CLIN-2272 - release

---

dags/lib/config.py
dags/lib/franklin.py
dags/lib/groups/franklin_create.py
dags/lib/groups/franklin_update.py
dags/lib/groups/ingest_batch.py
dags/lib/groups/ingest_fhir.py
dags/sensors/franklin.py

Will help us to validate VCFs before first import + refactoring code

feat: CLIN-2513 - validate VCFs

---

dags/etl.py
dags/etl_cleanup.py
dags/etl_import_fhir.py
dags/etl_import_franklin.py
dags/etl_import_varsome.py
dags/etl_ingest.py
dags/etl_migrate.py
dags/etl_notify.py
dags/etl_qa.py
dags/etl_qc.py
dags/etl_rolling.py
dags/lib/config.py
dags/lib/operators/spark.py
dags/scripts.py
dags/test_spark_fail.py

Retrofit des changements fait live pendant la release.

feat: CLIN-2610 more params for Airflow 2.7+

---

dags/lib/franklin.py

Franklin return error 500 if we ask too much status at once (100+ in our use case)
Ask for status by chunks

feat: CLIN-2704 franklin status by chunk

---

dags/lib/config.py
dags/lib/doc/qa.py
dags/lib/doc/qc.py
dags/lib/groups/qa.py
dags/lib/groups/qc.py
dags/lib/tasks/qa.py

Add
- NonDuplicationCoverageByGene
- ColumnsContainNoNullCoverageByGene
- ColumnsContainNoNullVariantCentric_FreqRQDM
- ColumnsContainOnlyNullCoverageByGene
- ColumnsContainOnlyNullVariantCentric_ExoMax
- ColumnsContainOnlyNullVariantCentric_FraMax
- ColumnsContainSameValueCoverageByGene
- ColumnsContainSameValueVariantCentric_ExoMax
- ColumnsContainSameValueVariantCentric_FraMax
Split ColumnsContainNoNullVariantCentric
- ColumnsContainNoNullVariantCentric
- ColumnsContainNoNullVariantCentric_Donors
- ColumnsContainNoNullVariantCentric_FreqByAnal
Split ColumnsContainOnlyNullVariantCentric
- ColumnsContainOnlyNullVariantCentric
- ColumnsContainOnlyNullVariantCentric_Clinvar
- ColumnsContainOnlyNullVariantCentric_CMC
- ColumnsContainOnlyNullVariantCentric_Consequences
- …

feat: CLIN-2853 Add and adjust etl_qa and etl_qc tests

---

dags/lib/doc/qc.py
dags/lib/groups/qc.py

- closes #CLIN-2519
[CLIN-2519](https://ferlab-crsj.atlassian.net/browse/CLIN-2519)
[CLIN-2519]: https://ferlab-crsj.atlassian.net/browse/CLIN-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: CLIN-2519 Add DataTest vcf_snv_somatic

---

dags/etl.py
dags/lib/config.py
dags/lib/operators/nextflow.py
dags/lib/operators/spark_etl.py
dags/lib/tasks/enrich.py
dags/lib/tasks/nextflow.py
dags/lib/tasks/normalize.py
dags/lib/tasks/prepare_index.py

+ Create a SparkETLOperator to simplify task creation for ETL tasks

feat: CLIN-3207 Run nextflow svclustering parental origin on germline CNVs

---

dags/lib/config.py
dags/lib/config_nextflow.py
dags/lib/config_operators.py

This new nextflow pipelien version support a batching behaviour that we think can help to improve the performance.

feat: BIOINFO-37 update ferlab-svclustering nextflow pipeline to 1.3

---

dags/etl_rolling_auto.py
dags/lib/slack.py
dags/sensors/rolling.py

Will automaticaly perform the ES rolling for FHIR aliases on QA
Every minute starting at 2am and for the duration of the day (16h)

feat: CLIN-3964 - DAG rolling FHIR auto

---

dags/lib/config.py

Adds clinical signs to enriched_clinical table

build: CLIN-3913 Update etl qa spark jar to v3.8.3

---

dags/etl_run.py

Add an extra step in the etl_run to dag to update ETL tables based on fhir data.
It will do the fhir export, re-create the fhir normalized tables, and then re-create the etl_enrich table.
The fhir import step is skipped because the clinical data should be already imported in fhir via the prescription api.
- ✨  Add an extra step in the etl_run to dag to update ETL tables based on fhir data. We reuse the fhir_ingest group.
- Also introduce the color and spark_jar parameters
- Introduce an extra task (validate_color) to validate the color parameter at the beginning of the dag.
Triggered the DAG manually from my computer, pointing to the QA clusters and MinIO.
**Manual Execution, with Valid color**
Started the DAG manually with a valid color (blue). 
- The DAG executed successfully
- Fhir …

feat: CLIN-3726 add fhir export, normalize and enrich etl steps

---

dags/etl_import_panels.py

Similar to `etl_cnv_frequencies` add enrich + prepare +index +delete previous release of variants centric to the DAG

feat: CLIN-3778 - import panels

---

dags/lib/config.py

To introduce these changes from `clin-variant-etl`:  https://github.com/Ferlab-Ste-Justine/clin-variant-etl/pull/452
> ## 🛠️ Changes
> ✨ Added bioinfo_analysis column in enriched_clinical table
> ✏️ Corrected GEAN to GEBA across the codebase, which is the actual value used for bioinfo_analysis_code

build: CLIN-4312 Bump QA spark jar to v3.8.10

---

dags/lib/config.py

Nouveau partitionnement par analysis id pour les tables normalized_snv, normalized_exomiser et normalized_coverage_by_gene.

feat: CLIN-4897-bump-clin-variant-etl-to-v3.17.0

---

dags/lib/config.py

This new version include the repartioning of the table normalized_variants

feat: CLIN-4920 bump clin-variant-etl version to v3.18.0

---

dags/lib/config.py

To benefit performance optimizations in normalized_variants spark job

fix: CLIN-4920 bump clin-variant-etl version to v3.18.1

---

dags/etl_cnv_frequencies.py
dags/lib/config.py
dags/lib/doc/cnv_frequencies.py
dags/lib/doc/qa.py
dags/lib/groups/qa.py
dags/lib/tasks/qa.py

* [feat: CLIN-5077 Bump QA Spark jar to v3.19.3-rollback-normalized-variants](https://github.com/Ferlab-Ste-Justine/clin-pipelines-dags/pull/662/commits/9071cb05bb143deb2468a043f4390b37735c5ec9)
* [feat: CLIN-3816 Update cnv_frequencies doc](https://github.com/Ferlab-Ste-Justine/clin-pipelines-dags/pull/662/commits/7089b52b60233f71eff07dcc268b900d16778962)
* [feat: CLIN-3816 Update nextflow svclustering QA tests](https://github.com/Ferlab-Ste-Justine/clin-pipelines-dags/pull/662/commits/b4aa7bc9d8e78fe56f624e0663936cb9e1011cda)

feat: CLIN-5077 Bump QA Spark jar to v3.19.3-rollback-normalized-variants

---

dags/etl_run.py
dags/lib/tasks/params_validate.py

Quand le DAG est appele via l'API hybrid on ne connait pas la couleur en QA.

fix: CLIN-5156 - resolve etl_run API request color param
